USE committee_manager;

ALTER TABLE members
  ADD COLUMN deleted_at BIGINT NULL DEFAULT NULL,
  ADD COLUMN deleted_by VARCHAR(255) NULL DEFAULT NULL;

ALTER TABLE settings MODIFY COLUMN next_id INT NOT NULL DEFAULT 1;
